# Generated by Django 3.1.3 on 2021-02-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('Availability', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=None)),
            ],
        ),
    ]
