# Generated by Django 3.1.3 on 2021-02-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210204_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
